language: zh
pipeline:
  # - name: HFTransformersNLP
  #   model_name: "bert"
  #   model_weights: "bert-base-chinese"
  # - name: "LanguageModelTokenizer"
  # - name: "LanguageModelFeaturizer"
  - name: JiebaTokenizer
    dictionary_path: /Users/kevinfan/code/nlu/first_rasa/words.txt
    intent_tokenization_flag: true
  # - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  # - name: CountVectorsFeaturizer
  - name: CRFEntityExtractor
  - name: DIETClassifier
    entity_recognition: false
  # epochs: 300
# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
