language: zh
pipeline:
  - name: HFTransformersNLP
    model_weights: "bert-base-chinese"
    model_name: "bert"
  - name: LanguageModelTokenizer
  - name: LanguageModelFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 20
    learning_rate: 0.001
    num_transformer_layers: 2
    embedding_dimension: 20
    weight_sparcity: 0.80
    use_masked_language_model: True
    # hidden_layer_sizes:
    #   text: [256, 128]
